# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [386]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [387]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [388]:
print(np.__version__,'\n=========================================================================================')
np.show_config()

1.23.4 
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMB

#### 3. Create a null vector of size 10 (★☆☆)

In [389]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [390]:
a.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [391]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [392]:
vo=np.zeros(10)
vo[4]=1
vo

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [393]:
rng=np.arange(10,50)
rng

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [394]:
rng[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [395]:
three=np.arange(1,26)
three.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [396]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [397]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [398]:
np.random.random((3,3))

array([[0.91839832, 0.17413105, 0.95443998],
       [0.80244709, 0.1762091 , 0.261758  ],
       [0.21440938, 0.32196109, 0.0663546 ]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [399]:
tt=np.random.random((10,10))
print('Min:\t',tt.min(),'\nMax:\t',tt.max())

Min:	 0.020565554614898396 
Max:	 0.9903129404317026


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [400]:
meanVec=np.random.random(25)
print('Vector:\n',meanVec,'\nMean:\t',meanVec.mean())

Vector:
 [8.39813646e-01 6.68046090e-01 8.22352783e-01 7.78062083e-02
 1.76543182e-01 2.81728959e-01 4.05328894e-01 3.14128908e-01
 2.12483109e-01 6.41028912e-01 7.93204405e-01 1.85093863e-01
 3.68510890e-01 8.36670468e-01 9.67253751e-01 1.41153970e-02
 1.82484664e-01 2.08960191e-01 4.41048709e-01 2.56907753e-05
 7.97187557e-01 9.40413099e-01 8.22285382e-01 1.36730114e-01
 8.92670421e-01] 
Mean:	 0.48103661168308554


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [401]:
arr2d=np.ones((5,5))
arr2d[1:-1, 1:-1]=0
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [402]:
bor=np.arange(11,20)
bor3=bor.reshape((3,3))
np.pad(bor3,1,'constant',constant_values=0)

array([[ 0,  0,  0,  0,  0],
       [ 0, 11, 12, 13,  0],
       [ 0, 14, 15, 16,  0],
       [ 0, 17, 18, 19,  0],
       [ 0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [403]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [404]:
np.diag((1,2,3,4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [405]:
cb=np.zeros((8,8))
cb[1::2, ::2] = 1
cb[::2, 1::2] = 1
cb

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [406]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [407]:
board=np.array(([0,1],[1,0]))
np.tile(board,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [408]:
bor=np.random.random((5,5))
m=np.mean(bor)
s=np.std(bor)
print(bor,'\n==================================================================\n',((bor-m)/s))

[[0.18611946 0.20628309 0.19129278 0.06085338 0.67708829]
 [0.68949177 0.26960354 0.76608456 0.00165977 0.40093721]
 [0.7713919  0.60611281 0.12381325 0.92087368 0.96152309]
 [0.43498208 0.75272104 0.56700488 0.53864781 0.38089618]
 [0.53228159 0.05510194 0.90071066 0.09169675 0.0332932 ]] 
 [[-0.85382916 -0.78727967 -0.83675477 -1.26726633  0.7665996 ]
 [ 0.80753693 -0.57829233  1.06032928 -1.46263319 -0.14482926]
 [ 1.07784601  0.53234702 -1.05946908  1.57120641  1.70536864]
 [-0.03246512  1.01622337  0.40327243  0.3096807  -0.21097412]
 [ 0.28866916 -1.28624882  1.50465895 -1.16546869 -1.35822796]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [409]:
ft=(np.arange(15)).reshape(5,3)
tt=(np.arange(6)).reshape(3,2)
print(ft@tt,'\n==============\n',np.dot(ft,tt))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]] 
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [410]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [411]:
Z=2
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

4
2
False
2j
2.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [412]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Admin\AppData\Local\Temp\ipykernel_13600\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Admin\AppData\Local\Temp\ipykernel_13600\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [413]:
Z = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(Z)), Z)

array([  5.,  -9.,  -9.,   9.,  -3.,   6.,  -8., -10.,  -6.,   9.])

#### 30. How to find common values between two arrays? (★☆☆)

In [414]:
a=[1,2,3,4,5]
b=[3,2,5,7,3,9]
np.intersect1d(a,b)

array([2, 3, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [415]:
with np.errstate(all='ignore'):
    np.arange(3)/0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [416]:
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


C:\Users\Admin\AppData\Local\Temp\ipykernel_13600\3643901316.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)==np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [417]:
yes=np.datetime64('today','D')-np.timedelta64(1,'D')
to=np.datetime64('today','D')
tom=np.datetime64('today','D')+np.timedelta64(1,'D')
print('Yesterday:\t',yes,'\nToday:\t',to,'\nTommorow:\t',tom)

Yesterday:	 2022-11-08 
Today:	 2022-11-09 
Tommorow:	 2022-11-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [418]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [419]:
A = np.ones(3)*1
B = np.ones(3)*2
c=np.multiply(np.negative(np.divide(A,2)),np.add(A,B))
d=((A+B)*(-A/2))
print(A)
print(B)
print(c)
print(d)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [420]:
ar=np.random.uniform(10,20,10)
print(ar,'\n-----1-----\n',ar.astype(int),'\n-----2-----\n',np.ceil(ar)-1,'\n-----3-----\n',ar-ar%1,'\n-----4-----\n',np.trunc(ar),'\n-----5-----\n',np.array(ar,int))


[17.67815297 15.22884982 18.43199374 14.21335143 12.63286953 19.60877669
 13.31017739 19.55558456 11.21801732 12.63003414] 
-----1-----
 [17 15 18 14 12 19 13 19 11 12] 
-----2-----
 [17. 15. 18. 14. 12. 19. 13. 19. 11. 12.] 
-----3-----
 [17. 15. 18. 14. 12. 19. 13. 19. 11. 12.] 
-----4-----
 [17. 15. 18. 14. 12. 19. 13. 19. 11. 12.] 
-----5-----
 [17 15 18 14 12 19 13 19 11 12]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [421]:
arr = np.zeros((5,5))
arr+np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [422]:
rng=np.random.default_rng()
rng.integers(5, size=10)

array([0, 3, 1, 3, 4, 2, 0, 2, 1, 1], dtype=int64)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [423]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [424]:
rng=np.random.default_rng()
abc=rng.integers(5, size=10)
np.sort(abc)

array([0, 1, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [425]:
print(abc,'\n',sum(abc),'\n',np.sum(abc),'\n',np.add.reduce(abc))

[2 4 3 4 3 2 1 3 0 4] 
 26 
 26 
 26


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [426]:
A = np.ones(3)*1
B = np.ones(3)*2
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [427]:
A[2]=123
print(A)
A.flags.writeable=False
A[1]=123
print(A)

[  1.   1. 123.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)