In [657]:
import numpy as np

In [658]:
a=np.array([[1,2],[4,5]],dtype=np.int32)
b=np.array([[7,8],[9,10]],dtype=np.int32)
print('uint32 type operation:\t',a.astype(np.uint32)-b.astype(np.uint32),'\nint32 type operation:\t',a-b)

uint32 type operation:	 [[4294967290 4294967290]
 [4294967291 4294967291]] 
int32 type operation:	 [[-6 -6]
 [-5 -5]]


In [659]:
np.arange(2,10,1.2,dtype=float)

array([2. , 3.2, 4.4, 5.6, 6.8, 8. , 9.2])

In [660]:
np.linspace(2,10,7,dtype=float)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [661]:
np.eye(6,6,2,dtype=int)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [662]:
d=np.diag([11,21,31,41])
d

array([[11,  0,  0,  0],
       [ 0, 21,  0,  0],
       [ 0,  0, 31,  0],
       [ 0,  0,  0, 41]])

In [663]:
np.diag(d)

array([11, 21, 31, 41])

In [664]:
v=np.arange(2,10,2,dtype=int) 
v

array([2, 4, 6, 8])

In [665]:
van=np.vander(v,4)
van

array([[  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1],
       [512,  64,   8,   1]])

In [666]:
np.zeros((2,4,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [667]:
np.ones((2,4,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [668]:
from numpy.random import default_rng
default_rng(5).random((2,4,3))
#default_rng(5), where 5 is the seed value 
#Seed value is used to generate the same random set everytime, when same seed value is provided.

array([[[0.80500292, 0.80794079, 0.51532556],
        [0.28580138, 0.0539307 , 0.38336888],
        [0.40847321, 0.04527519, 0.04875771],
        [0.99917612, 0.65236911, 0.2345102 ]],

       [[0.43494755, 0.97418619, 0.89767761],
        [0.84423104, 0.39240466, 0.49302302],
        [0.67668935, 0.06080271, 0.55559612],
        [0.2714516 , 0.87965117, 0.06421444]]])

In [669]:
np.indices((3,4))

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [670]:
b = v[:3].copy()
b *= 2
print('v =\t', v, '\nb =\t', b)

v =	 [2 4 6 8] 
b =	 [ 4  8 12]


In [671]:
b = v[:3]
b *= 2
print('v =\t', v, '\nb =\t', b)

v =	 [ 4  8 12  8] 
b =	 [ 4  8 12]


In [672]:
np.loadtxt('sample.csv', delimiter = ',', skiprows = 1, dtype=int) 

array([[0, 0],
       [1, 1],
       [2, 4],
       [3, 9]])

In [673]:
i=np.arange(0,16,3)
print(i)
i.shape=(2,3)
print('Shaped Array:\n',i)
print('Array index 1 :\n',i[1])

[ 0  3  6  9 12 15]
Shaped Array:
 [[ 0  3  6]
 [ 9 12 15]]
Array index 1 :
 [ 9 12 15]


In [674]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[2::3]

array([2, 5, 8])

In [675]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]],[[7],[8],[9]]])
y[1:3]
z=y[..., 0]
z[:,None]

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [676]:
na=np.arange(0,2,0.5)
na[:,None]+na[None,:]

array([[0. , 0.5, 1. , 1.5],
       [0.5, 1. , 1.5, 2. ],
       [1. , 1.5, 2. , 2.5],
       [1.5, 2. , 2.5, 3. ]])

In [677]:
print('X= ',x)
print('Indexing on X\n',x[np.array([[-2,-2],[-1,-6]])])
print('van=\n',van,'\n-------\n')
print('Indexing X and Y\n',van[np.array([1,2]),np.array([0,3])])
print('Indexing X and y=1\n',van[np.array([1,2]),0])
print('Indexing only X\n',van[np.array([1,2])])
r1=van[np.array([2,2]),np.array([0,1])]
r2=van[np.array([3,3]),np.array([0,1])]
print('Advance Indexing\n',np.array([r1,r2]))

X=  [0 1 2 3 4 5 6 7 8 9]
Indexing on X
 [[8 8]
 [9 4]]
van=
 [[  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]
 [512  64   8   1]] 
-------

Indexing X and Y
 [64  1]
Indexing X and y=1
 [ 64 216]
Indexing only X
 [[ 64  16   4   1]
 [216  36   6   1]]
Advance Indexing
 [[216  36]
 [512  64]]


In [678]:
x = np.array([1., -2.,np.nan, 3.,np.nan, np.nan])
y=x[~np.isnan(x)]
y[y < 0] += 20
y

array([ 1., 18.,  3.])

In [679]:
print('van=\n',van,'\n-------')
print('van 1st col ====',van[:,1],'\n-------')
x = np.arange(35).reshape(5, 7)
b = x > 20
print('x=\n',x,'\n-------')
print('x 4th col ====',x[:,4],'\n-------')
print('b=\n',b,'\n-------')
print('b 5th col ====',b[:,5],'\n-------')

van=
 [[  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]
 [512  64   8   1]] 
-------
van 1st col ==== [ 4 16 36 64] 
-------
x=
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]] 
-------
x 4th col ==== [ 4 11 18 25 32] 
-------
b=
 [[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]] 
-------
b 5th col ==== [False False False  True  True] 
-------


In [691]:
x = np.array([[0, 1], [4, 1], [2, 2]])
rowsum = x.sum(-1)
print('Rowsome of x= ',rowsum,'\nIf rowsome is <= 4\n',x[rowsum <= 4, :])

Rowsome of x=  [1 5 4] 
If rowsome is <= 4
 [[0 1]
 [2 2]]


In [694]:
ix = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rowx=(ix.sum(-1) % 2) == 0
print(rowx)
columns = [0, 1]
x[np.ix_(rowx, columns)]

[False  True False  True]


array([[ 3,  4],
       [ 9, 10]])